package com.ethan.quartzconsole.meta;

public abstract interface QuartzAttributes
{
  public static final String SCHEDULER_JOB_STORE_CLASS_NAME = "JobStoreClassName";
  public static final String SCHEDULER_SCHEDULER_INSTANCE_ID = "SchedulerInstanceId";
  public static final String SCHEDULER_SCHEDULER_NAME = "SchedulerName";
  public static final String SCHEDULER_STARTED = "Started";
  public static final String SCHEDULER_STANDBY_MODE = "StandbyMode";
  public static final String SCHEDULER_THREAD_POOL_CLASS_NAME = "ThreadPoolClassName";
  public static final String SCHEDULER_THREAD_POOL_SIZE = "ThreadPoolSize";
  public static final String SCHEDULER_VERSION = "Version";
  public static final String SCHEDULER_TYPE = "Type";
  public static final String SCHEDULER_NODE = "Node";
  public static final String SCHEDULER_CURRENTLY_EXECUTING_JOBS = "CurrentlyExecutingJobs";
  public static final String JOB_DESCRIPTION = "description";
  public static final String JOB_DURABILITY = "durability";
  public static final String JOB_GROUP = "group";
  public static final String JOB_JOB_CLASS = "jobClass";
  public static final String JOB_JOB_DATA_MAP = "jobDataMap";
  public static final String JOB_NAME = "name";
  public static final String JOB_SHOULD_RECOVER = "shouldRecover";
  public static final String JOB_VOLATILITY = "volatility";
  public static final String TRIGGER_CALENDAR_NAME = "calendarName";
  public static final String TRIGGER_DESCRIPTION = "description";
  public static final String TRIGGER_END_TIME = "endTime";
  public static final String TRIGGER_FINAL_FIRE_TIME = "finalFireTime";
  public static final String TRIGGER_FIRE_INSTANCE_ID = "fireInstanceId";
  public static final String TRIGGER_JOB_DATA_MAP = "jobDataMap";
  public static final String TRIGGER_JOB_GROUP = "jobGroup";
  public static final String TRIGGER_JOB_NAME = "jobName";
  public static final String TRIGGER_MISFIRE_CONSTRUCTION = "misfireInstruction";
  public static final String TRIGGER_GROUP = "group";
  public static final String TRIGGER_NAME = "name";
  public static final String TRIGGER_NEXT_FIRE_TIME = "nextFireTime";
  public static final String TRIGGER_PREVIOUS_FIRE_TIME = "previousFireTime";
  public static final String TRIGGER_PRIORITY = "priority";
  public static final String TRIGGER_START_TIME = "startTime";
  public static final String TRIGGER_VOLATILITY = "volatility";
  public static final String NOTIFICATION_CALENDAR_NAME = "calendarName";
  public static final String NOTIFICATION_FIRE_TIME = "fireTime";
  public static final String NOTIFICATION_JOB_DATA_MAP = "jobDataMap";
  public static final String NOTIFICATION_JOB_NAME = "jobName";
  public static final String NOTIFICATION_JOB_GROUP_NAME = "jobGroup";
  public static final String NOTIFICATION_JOB_RUN_TIME = "jobRunTime";
  public static final String NOTIFICATION_NEXT_FIRE_TIME = "nextFireTime";
  public static final String NOTIFICATION_PREVIOUS_FIRE_TIME = "previousFireTime";
  public static final String NOTIFICATION_RECOVERING = "recovering";
  public static final String NOTIFICATION_REFIRE_COUNT = "refireCount";
  public static final String NOTIFICATION_SCHEDULED_FIRE_TIME = "scheduledFireTime";
  public static final String NOTIFICATION_SCHEDULER_NAME = "schedulerName";
  public static final String NOTIFICATION_TRIGGER_NAME = "triggerName";
  public static final String NOTIFICATION_TRIGGER_GROUP_NAME = "triggerGroup";
  public static final String NOTIFICATION_FIRE_INSTANCE_ID = "fireInstanceId";
}